version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: shop
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shop-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: