services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # ← УБРАЛИ volumes
    networks:
      - medusa_network

  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  medusa:
    build: .
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa-store
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    # ← УБРАЛИ volumes
    networks:
      - medusa_network

  payload:
    build:
      context: ../payload-cms
    container_name: payload_cms
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PAYLOAD_SECRET=supersecretpassword123
      - PAYLOAD_DATABASE_URL=postgres://postgres:postgres@postgres:5432/payload
    # ← УБРАЛИ volumes
    networks:
      - medusa_network

networks:
  medusa_network:
    driver: bridge
